CREATE DATABASE IF NOT EXISTS testdb;
USE testdb;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    token VARCHAR(500)
);

INSERT INTO users (email, password) VALUES ('admin@example.com', '123456') 
ON DUPLICATE KEY UPDATE password='123456';
